# Generated by Django 4.1.2 on 2022-11-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='region',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
