# Generated by Django 4.1.2 on 2022-11-12 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0002_alter_bucket_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='resource',
        ),
    ]
