# Generated by Django 4.1.2 on 2022-11-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0003_remove_statement_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='action',
            field=models.ManyToManyField(to='s3.action'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='principal',
            field=models.ManyToManyField(to='s3.client'),
        ),
    ]
