# Generated by Django 4.1.2 on 2022-11-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0005_alter_policy_bucket_alter_statement_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='action',
            field=models.ManyToManyField(db_constraint=False, to='s3.action'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='principal',
            field=models.ManyToManyField(db_constraint=False, to='s3.client'),
        ),
    ]
